{
 "title": "Hands On K8S",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "/users Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(request_duration_seconds_count{path=\"/users\", status=\"200\", job=\"$service\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "/users Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * (sum without(status)(rate(request_duration_seconds_sum{path=\"/users\", job=\"$service\"}[5m])) / sum without (status)(rate(request_duration_seconds_count{path=\"/users\", job=\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "/users Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum without(status)(rate(request_duration_seconds_count{path=\"/users\", job=\"$service\", status=~\"5..\"}[5m])) / sum without(status)(rate(request_duration_seconds_count{path=\"/users\", job=\"$service\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}