apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hands-on-ingress
  namespace: handson
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hands-on-web
          servicePort: 4431