apiVersion: apps/v1
kind: Deployment
metadata:
  name: hands-on-user-service
  namespace: handson
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: hands-on-user-service
  template:
    metadata:
      labels:
        app: hands-on-user-service
    spec:
      containers:
      - name: user-service
        env: 
        - name: PORT
          value: "4432"
        image: hands-on-k8s-user-service:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 4432
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 4432
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 4432
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 1

