apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hands-on-user-service
  labels:
    app: hands-on-user-service
    prometheus: k8s
spec:
  endpoints:
  - port: http
    path: '/metrics'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: hands-on-user-service