apiVersion: v1
kind: Service
metadata:
  name: hands-on-user-service
  namespace: handson
  labels:
    app: hands-on-user-service
spec:
  selector:
    app: hands-on-user-service
  ports:
  - port: 4432
    targetPort: 4432
    protocol: TCP
    name: http
